# Generated by Django 5.0.6 on 2024-06-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_meal_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('food_group', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(verbose_name='meal date'),
        ),
        migrations.AddField(
            model_name='soup',
            name='ingredients',
            field=models.ManyToManyField(to='main_app.ingredients'),
        ),
    ]
